[options]
# :h SpaceVim-config
# :h g:spacevim_buffer_index_type
buffer_index_type = 1
enable_os_fileformat_icon = 1
enable_statusline_display_mode = 1
enable_tabline_filetype_icon = 1
enable_vimfiler_welcome = 1
statusline_separator = "bar"

# https://github.com/SpaceVim/SpaceVim/blob/master/docs/documentation.md#font
# "changing this value has no effect if you are running Vim/Neovim in terminal."
# https://www.iterm2.com/documentation-fonts.html
# guifont = 'Source Code Pro Medium for Powerline'
# guifont = 'Hack Regular Nerd Font Complete'

# layers:colorscheme
# https://spacevim.org/layers/colorscheme/
colorscheme="mycontrast"
colorscheme_bg = "dark"
background = "dark"

# custom_plugins options
# https://spacevim.org/documentation/#bootstrap-functions
bootstrap_before = "myspacevim#before"
bootstrap_after = "myspacevim#after"

[[custom_plugins]]
# https://github.com/napcs/vim-mycontrast
name = "napcs/vim-mycontrast"

[[custom_plugins]]
# https://github.com/mhartington/oceanic-next
name = "mhartington/oceanic-next"
merged = 0

[[custom_plugins]]
# https://github.com/ambv/black#editor-integration
name = "ambv/black"
merged = 0
on_ft = "python"

[[custom_plugins]]
# https://github.com/fisadev/vim-isort
name = "fisadev/vim-isort"
merged = 0
on_ft = "python"

[[custom_plugins]]
name = "godlygeek/tabular.git"
merged = 0
on_ft = "markdown"

[[layers]]
name = "autocomplete"
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "cycle"

[[layers]]
name = "colorscheme"

[[layers]]
name = "cscope"

[[layers]]
name = "java"

[[layers]]
name = "python"
# pip install jedi isort black pylama eradicate

[[layers]]
name = "scala"

[[layers]]
name = "shell"
default_position = "top"
default_height = 30

[[layers]]
name = "vim"
# pip install vint vim-vint


