[options]
# :h SpaceVim-config
# :h g:spacevim_buffer_index_type
# https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim.vim
buffer_index_type              = 1
enable_guicolors               = 1
enable_os_fileformat_icon      = 1
enable_statusline_display_mode = 1
enable_tabline_filetype_icon   = 1
enable_vimfiler_filetypeicon   = 0
enable_vimfiler_gitstatus      = 1
enable_vimfiler_welcome        = 0  # XXX: very slow, source code also confirmed it.
max_column                     = 120
plugin_manager                 = "dein"
project_rooter_automatically   = 0  # XXX: does not work if i edit a file in another project.
project_rooter_patterns        = [".git"]
relativenumber                 = 0
search_tools                   = ["rg", "ag", "grep"]
snippet_engine                 = "ultisnips"
# snippet_engine                 = "neosnippet"
statusline_separator           = "bar"
vimcompatible                  = 0

# https://github.com/SpaceVim/SpaceVim/blob/master/docs/documentation.md#font
# "changing this value has no effect if you are running Vim/Neovim in terminal."
# https://www.iterm2.com/documentation-fonts.html
# guifont = "Source Code Pro Medium for Powerline"
guifont = "Sauce Code Pro Nerd Font Complete Mono"

# custom_plugins options
# https://spacevim.org/documentation/#bootstrap-functions
bootstrap_before = "myspacevim#before"
bootstrap_after  = "myspacevim#after"

# layers:colorscheme
# https://spacevim.org/layers/colorscheme/
colorscheme    = "molokai"
colorscheme_bg = "dark"

# layers:checkers
enable_neomake = false
enable_ale     = true

# ==============================================================================

# ##^^ colorscheme ^^## --------------------------------------------------------

# [[custom_plugins]]
# # https://github.com/napcs/vim-mycontrast
# name = "napcs/vim-mycontrast"
# merged = 0
#
# [[custom_plugins]]
# # https://github.com/marcopaganini/termschool-vim-theme
# name = "marcopaganini/termschool-vim-theme"

# ##$$ colorscheme $$## --------------------------------------------------------


# ##^^ Python ^^## -------------------------------------------------------------

[[custom_plugins]]
# https://github.com/ambv/black#editor-integration
name = "ambv/black"
merged = 0
on_ft = "python"

[[custom_plugins]]
# https://github.com/fisadev/vim-isort
name = "fisadev/vim-isort"
merged = 0
on_ft = "python"

# ##$$ Python $$## -------------------------------------------------------------

# code formatters
# java: brew install astyle uncrustify
# markdown: npm install remark-cli
# python: pip install black isort yapf
# scala: brew install scalariform scalafmt scalastyle
# shell: go get -u mvdan.cc/sh/cmd/shfmt
# sql: pip install sqlparser # sqlformat

[[custom_plugins]]
# https://github.com/Chiel92/vim-autoformat
name = "Chiel92/vim-autoformat"

[[custom_plugins]]
# https://vimawesome.com/plugin/neoformat
name = "sbdchd/neoformat"

[[custom_plugins]]
# https://github.com/godlygeek/tabular
name = "godlygeek/tabular"
merged = 0
on_ft = "markdown"

[[custom_plugins]]
# for Gbrowse
# https://github.com/tpope/vim-rhubarb
name = "tpope/vim-rhubarb"
merged = 0

[[custom_plugins]]
# https://github.com/tpope/vim-fugitive
name = "tpope/vim-fugitive"
merged = 0

# [[custom_plugins]]
# name = "ryanolsonx/vim-lsp-python"
# merged = 0

# [[custom_plugins]]
# name = "vim-scripts/dbext.vim"
# merged = 0"

# [[custom_plugins]]
# # https://github.com/Shougo/deoplete.nvim
# name = "Shougo/deoplete.nvim"
# merged = 0
#
# # Explains why the below 2 plugins are needed.
# # https://github.com/Shougo/deoplete.nvim#requirements
# # for neovim :UpdateRemotePlugins
# [[custom_plugins]]
# # https://github.com/roxma/nvim-yarp
# name = "roxma/nvim-yarp"
#
# [[custom_plugins]]
# # https://github.com/roxma/vim-hug-neovim-rpc
# name = "roxma/vim-hug-neovim-rpc"

# [[custom_plugins]]
# # https://github.com/editorconfig/editorconfig-vim
# name = "editorconfig/editorconfig-vim"
# merged = 0

[[custom_plugins]]
# https://github.com/lepture/vim-jinja
name = "lepture/vim-jinja"
merged = 0

[[custom_plugins]]
# https://github.com/jremmen/vim-ripgrep
name = "jremmen/vim-ripgrep"
merged = 0

# use customized plugin instead of layer for quickfix/location list window
[[custom_plugins]]
# https://github.com/ludovicchabant/vim-gutentags
name = "ludovicchabant/vim-gutentags"
merged = 0

[[custom_plugins]]
# https://github.com/skywind3000/gutentags_plus
name = "skywind3000/gutentags_plus"
merged = 0

[[custom_plugins]]
# https://github.com/cespare/vim-toml
name = "cespare/vim-toml"
merged = 0

[[custom_plugins]]
# https://github.com/junegunn/fzf
name = "junegunn/fzf"
merged = 0

[[custom_plugins]]
# https://github.com/junegunn/fzf.vim
name = "junegunn/fzf.vim"
merged = 0

[[custom_plugins]]
# https://github.com/srstevenson/vim-picker
name = "srstevenson/vim-picker"
merged = 0

[[custom_plugins]]
# https://github.com/airblade/vim-rooter
name = "airblade/vim-rooter"
merged = 0

[[custom_plugins]]
# https://github.com/luochen1990/rainbow
name = "luochen1990/rainbow"
merged = 0

# [[custom_plugins]]
# # https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim
# name = "neoclide/coc.nvim"
# # :help dein-options
# build = "yarn install"
# # call coc#util#install()

# [[custom_plugins]]
# # https://github.com/SirVer/ultisnips
# name = "SirVer/ultisnips"
# merged = 0

[[custom_plugins]]
# https://github.com/mtth/scratch.vim
name = "mtth/scratch.vim"
merged = 0

[[custom_plugins]]
# https://github.com/tpope/vim-scriptease
name = "tpope/vim-scriptease"
merged = 0

# XXX: https://spacevim.org/documentation/#unimpaired-bindings
# [[custom_plugins]]
# # https://github.com/tpope/vim-unimpaired/blob/master/doc/unimpaired.txt
# name = "tpope/vim-unimpaired"
# merged = 0

# ==============================================================================

[[layers]]
name = "colorscheme"

#[[layers]]
#name = "tools"

# fuzzyfinder layers
# [[layers]]
# name = "ctrlp"

[[layers]]
name = "denite"

# [[layers]]
# name = "fzy"

[[layers]]
name = "fzf"

[[layers]]
name = "VersionControl"

[[layers]]
name = "git"

[[layers]]
# https://spacevim.org/layers/autocomplete/#configuration
name = "autocomplete"
auto-completion-return-key-behavior = "nil"
auto-completion-tab-key-behavior = "smart"
auto-completion-delay = 200
auto-completion-complete-with-key-sequence = "nil"
auto-completion-complete-with-key-sequence-delay = 0.1

[[layers]]
name = "checkers"
show_cursor_error = false

[[layers]]
name = "cscope"

[[layers]]
name = "tags"

[[layers]]
name = "github"

#[[layers]]
#name = "lsp"
#filetypes = ["python", "sh"]
# https://github.com/prabirshrestha/vim-lsp/wiki/Servers-Python
# XXX: lsp is not stable enough, renaming support, requires setup etc

[[layers]]
name = "shell"
default_position = "top"
default_height = 30


[[layers]]
name = "lang#python"
# pip install jedi isort black pylama eradicate

[[layers]]
name = "lang#java"

[[layers]]
name = "lang#scala"

[[layers]]
name = "lang#vim"
# pip install vint vim-vint

[[layers]]
name = "lang#sh"
