[options]
# :h SpaceVim-config
# :h g:spacevim_buffer_index_type
buffer_index_type = 1
enable_guicolors = 1
enable_os_fileformat_icon = 1
enable_statusline_display_mode = 1
enable_tabline_filetype_icon = 1
enable_vimfiler_filetypeicon = 0
enable_vimfiler_gitstatus = 1
enable_vimfiler_welcome = 0  # very slow
max_column = 120
project_rooter_patterns = [".git"]
relativenumber = 0
statusline_separator = "bar"
vimcompatible = 0

# https://github.com/SpaceVim/SpaceVim/blob/master/docs/documentation.md#font
# "changing this value has no effect if you are running Vim/Neovim in terminal."
# https://www.iterm2.com/documentation-fonts.html
# guifont = 'Source Code Pro Medium for Powerline'
guifont = "Sauce Code Pro Nerd Font Complete Mono"

# custom_plugins options
# https://spacevim.org/documentation/#bootstrap-functions
bootstrap_before = "myspacevim#before"
bootstrap_after = "myspacevim#after"

# layers:colorscheme
# https://spacevim.org/layers/colorscheme/
colorscheme="molokai"
colorscheme_bg = "dark"

# ==============================================================================

# ##^^ colorscheme ^^## --------------------------------------------------------

[[custom_plugins]]
# https://github.com/napcs/vim-mycontrast
name = "napcs/vim-mycontrast"
merged = 0

[[custom_plugins]]
# https://github.com/marcopaganini/termschool-vim-theme
name = "marcopaganini/termschool-vim-theme"

# ##$$ colorscheme $$## --------------------------------------------------------


# ##^^ Python ^^## -------------------------------------------------------------

[[custom_plugins]]
# https://github.com/ambv/black#editor-integration
name = "ambv/black"
merged = 0
on_ft = "python"

[[custom_plugins]]
# https://github.com/fisadev/vim-isort
name = "fisadev/vim-isort"
merged = 0
on_ft = "python"

# ##$$ Python $$## -------------------------------------------------------------


[[custom_plugins]]
# https://github.com/Chiel92/vim-autoformat
name = "Chiel92/vim-autoformat"
# python: pip install black
# shell: go get -u mvdan.cc/sh/cmd/shfmt
# sql: pip install sqlparser # sqlformat

[[custom_plugins]]
# https://github.com/godlygeek/tabular
name = "godlygeek/tabular"
merged = 0
on_ft = "markdown"

[[custom_plugins]]
# https://github.com/tpope/vim-fugitive
name = "tpope/vim-fugitive"
merged = 0

#[[custom_plugins]]
#name = "ryanolsonx/vim-lsp-python"
#merged = 0

#[[custom_plugins]]
#name = "vim-scripts/dbext.vim"
#merged = 0"

# Explains why the below 2 plugins are needed.
# https://github.com/Shougo/deoplete.nvim#requirements
# for neovim :UpdateRemotePlugins
[[custom_plugins]]
# https://github.com/roxma/nvim-yarp
name = "roxma/nvim-yarp"

[[custom_plugins]]
# https://github.com/roxma/vim-hug-neovim-rpc
name = "roxma/vim-hug-neovim-rpc"

[[custom_plugins]]
# https://github.com/lepture/vim-jinja
name = "lepture/vim-jinja"
merged = 0

[[custom_plugins]]
# https://github.com/jremmen/vim-ripgrep
name = "jremmen/vim-ripgrep"
merged = 0

# use customized plugin instead of layer for quickfix/location list window
[[custom_plugins]]
# https://github.com/ludovicchabant/vim-gutentags
name = "ludovicchabant/vim-gutentags"
merged = 0

[[custom_plugins]]
# https://github.com/skywind3000/gutentags_plus
name = "skywind3000/gutentags_plus"
merged = 0

[[custom_plugins]]
# https://github.com/cespare/vim-toml
name = "cespare/vim-toml"
merged = 0

[[custom_plugins]]
name = "junegunn/fzf"
merged = 0

[[custom_plugins]]
# https://github.com/junegunn/fzf.vim
name = "junegunn/fzf.vim"
merged = 0

# ==============================================================================

[[layers]]
name = "colorscheme"

#[[layers]]
#name = "tools"

# fuzzyfinder layers
#[[layers]]
#name = "ctrlp"

#[[layers]]
#name = "denite"

#[[layers]]
#name = "fzy"

[[layers]]
name = "fzf"

[[layers]]
name = "git"

[[layers]]
name = "VersionControl"

[[layers]]
name = "autocomplete"
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "cycle"

#[[layers]]
#name = "cscope"

[[layers]]
name = "tags"

[[layers]]
name = "github"

#[[layers]]
#name = "lsp"
#filetypes = ["python", "sh"]
# https://github.com/prabirshrestha/vim-lsp/wiki/Servers-Python
# XXX: lsp is not stable enough, renaming support, requires setup etc

[[layers]]
name = "shell"
default_position = "top"
default_height = 30


[[layers]]
name = "lang#python"
# pip install jedi isort black pylama eradicate

[[layers]]
name = "lang#java"

[[layers]]
name = "lang#scala"

[[layers]]
name = "lang#vim"
# pip install vint vim-vint

[[layers]]
name = "lang#sh"

