[options]
# :h SpaceVim-config
# :h g:spacevim_buffer_index_type
# https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim.vim
buffer_index_type              = 1
enable_guicolors               = 1
enable_os_fileformat_icon      = 1
enable_statusline_display_mode = 1
enable_tabline_filetype_icon   = 1
enable_vimfiler_filetypeicon   = 0
enable_vimfiler_gitstatus      = 1
enable_vimfiler_welcome        = 0  # XXX: very slow, source code also confirmed it.
max_column                     = 120
# https://github.com/Shougo/dein.vim/blob/master/doc/dein.txt
plugin_manager                 = "dein"
# https://spacevim.org/documentation/#managing-projects
project_rooter_automatically   = 1
# XXX: directory pattern must use '/', see projectmanager.vim
project_rooter_patterns        = ["setup.cfg", "Pipfile", ".git/"]
relativenumber                 = 0
search_tools                   = ["rg", "ag", "grep"]
# https://github.com/SpaceVim/SpaceVim/blob/master/autoload/SpaceVim.vim#L296
# snippet_engine                 = "ultisnips"
snippet_engine                 = "neosnippet"
statusline_separator           = "arrow"
statusline_inactive_separator  = "arrow"
vimcompatible                  = 0

# https://github.com/SpaceVim/SpaceVim/blob/master/docs/documentation.md#font
# "changing this value has no effect if you are running Vim/Neovim in terminal."
# https://www.iterm2.com/documentation-fonts.html
# guifont = "Source Code Pro Medium for Powerline"
guifont = "HackNerdFontCompleteM-Regular:h13"

# custom_plugins options
# https://spacevim.org/documentation/#bootstrap-functions
bootstrap_before = "myspacevim#before"
bootstrap_after  = "myspacevim#after"

# layers:colorscheme
# https://spacevim.org/layers/colorscheme/
colorscheme    = "molokai"
colorscheme_bg = "dark"

# layers:checkers
enable_neomake = false
enable_ale     = true

# indentLine is too intrusive, cannot find an easy way to overwrite its setting
disabled_plugins = ['indentLine']

# ==============================================================================
[[layers]]
name = "colorscheme"

#[[layers]]
#name = "tools"

[[layers]]
name = "denite"

[[layers]]
name = "fzf"

[[layers]]
name = "VersionControl"

[[layers]]
name = "git"
git-plugin = "fugitive"

[[layers]]
# https://spacevim.org/layers/autocomplete/#configuration
name = "autocomplete"
auto-completion-return-key-behavior = "nil"
auto-completion-tab-key-behavior = "smart"
auto-completion-delay = 200
auto-completion-complete-with-key-sequence = "nil"
auto-completion-complete-with-key-sequence-delay = 0.1

[[layers]]
name = "checkers"
show_cursor_error = false

# XXX: annoying message "all databases has been cleared!"
# https://github.com/SpaceVim/cscope.vim/blob/master/autoload/cscope.vim#L87
# [[layers]]
# name = "cscope"

# XXX: maybe some conflict with Gutentags? just use Gtags
# "failed to update gtags, exit data: 1"
# [[layers]]
# # https://spacevim.org/layers/gtags/
# name = "gtags"
# gtagslabel = "pygments"

# [[layers]]
# name = "github"

#[[layers]]
#name = "lsp"
#filetypes = ["python", "sh"]
# https://github.com/prabirshrestha/vim-lsp/wiki/Servers-Python
# XXX: lsp is not stable enough, renaming support, requires setup etc

[[layers]]
name = "shell"
default_position = "top"
default_height = 30

[[layers]]
name = "lang#python"
# pip install jedi isort black pylama eradicate
python-file-head = [
  '#!/usr/bin/env python3',
  '',
  '"""'
  '<Module Description>'
  '"""',
  ''
]

# [[layers]]
# name = "lang#java"

[[layers]]
name = "lang#scala"

[[layers]]
name = "lang#vim"
# pip install vint vim-vint

[[layers]]
name = "lang#sh"

# [[layers]]
# name = "lang#go"

# [[layers]]
# name = "tmux"
# tmux_navigator_modifier = "alt"
# tmuxline_separators_alt = "arrow"

# ==============================================================================
## colorscheme ##

[[custom_plugins]]
# https://github.com/drewtempelmeyer/palenight.vim
name = 'drewtempelmeyer/palenight.vim'
merged = 0

[[custom_plugins]]
# https://github.com/ayu-theme/ayu-vim
name = 'ayu-theme/ayu-vim'
merged = 0

[[custom_plugins]]
# https://draculatheme.com/vim/
name = 'dracula/vim'
merged = 0

[[custom_plugins]]
# https://github.com/NLKNguyen/papercolor-theme
name = "NLKNguyen/papercolor-theme"
merged = 0

[[custom_plugins]]
# https://github.com/jaredgorski/SpaceCamp
name = "jaredgorski/SpaceCamp"
merged = 0

[[custom_plugins]]
# https://github.com/haishanh/night-owl.vim
name = "haishanh/night-owl.vim"
merged = 0

[[custom_plugins]]
# https://github.com/reedes/vim-colors-pencil
name = "reedes/vim-colors-pencil"
merged = 0

# ------------------------------------------------------------------------------
## Python ##

[[custom_plugins]]
# https://github.com/ambv/black#editor-integration
name = "ambv/black"
merged = 0
on_ft = "python"

[[custom_plugins]]
# https://github.com/fisadev/vim-isort
name = "fisadev/vim-isort"
merged = 0
on_ft = "python"

[[custom_plugins]]
# https://github.com/numirias/semshi
name = "numirias/semshi"
merged = 0
if = "has('nvim')"
on_ft = "python"

# [[custom_plugins]]
# # https://github.com/ehamberg/vim-cute-python
# name = "ehamberg/vim-cute-python"
# merged = 0
# on_ft = "python"

[[custom_plugins]]
# https://github.com/janko/vim-test#setup
name = "janko/vim-test"
merged = 0

[[custom_plugins]]
# https://github.com/tpope/vim-dispatch#faq
name = "tpope/vim-dispatch"
merged = 0

# ------------------------------------------------------------------------------
## code formatters ##

# java: brew install astyle uncrustify
# markdown: npm install remark-cli
# python: pip install black isort yapf
# scala: brew install scalariform scalafmt scalastyle
# shell: go get -u mvdan.cc/sh/cmd/shfmt
# sql: pip install sqlparser # sqlformat

[[custom_plugins]]
# https://github.com/godlygeek/tabular
name = "godlygeek/tabular"
merged = 0
on_ft = "markdown"

# ------------------------------------------------------------------------------
## tags ##

[[custom_plugins]]
# https://github.com/vim-scripts/gtags.vim/blob/master/plugin/gtags.vim
name = "vim-scripts/gtags.vim"

# https://spacevim.org/layers/tags/
# use customized plugin instead of layer for quickfix/location list window
[[custom_plugins]]
# https://github.com/ludovicchabant/vim-gutentags
name = "ludovicchabant/vim-gutentags"
merged = 0

[[custom_plugins]]
# https://github.com/skywind3000/gutentags_plus
name = "skywind3000/gutentags_plus"
merged = 0

[[custom_plugins]]
# https://github.com/skywind3000/vim-preview
name = "skywind3000/vim-preview"
merged = 0

# ------------------------------------------------------------------------------
# ## git ##

# [[custom_plugins]]
# # https://github.com/jreybert/vimagit
# name = "jreybert/vimagit"
# merged = 0

# [[custom_plugins]]
# # https://github.com/tpope/vim-fugitive
# name = "tpope/vim-fugitive"
# merged = 0

[[custom_plugins]]
# https://github.com/mhinz/vim-signify
name = "mhinz/vim-signify"
merged = 0

# ------------------------------------------------------------------------------

[[custom_plugins]]
# for Gbrowse
# https://github.com/tpope/vim-rhubarb
name = "tpope/vim-rhubarb"
merged = 0

[[custom_plugins]]
# preview markdown
# https://github.com/previm/previm
name = "previm/previm"
merged = 0

# [[custom_plugins]]
# name = "ryanolsonx/vim-lsp-python"
# merged = 0

# [[custom_plugins]]
# name = "vim-scripts/dbext.vim"
# merged = 0"

# [[custom_plugins]]
# # https://github.com/editorconfig/editorconfig-vim
# name = "editorconfig/editorconfig-vim"
# merged = 0

# ------------------------------------------------------------------------------
# ## search ##

[[custom_plugins]]
# https://github.com/jremmen/vim-ripgrep
name = "jremmen/vim-ripgrep"
merged = 0

[[custom_plugins]]
# https://github.com/junegunn/fzf
name = "junegunn/fzf"
merged = 0

[[custom_plugins]]
# https://github.com/junegunn/fzf.vim
name = "junegunn/fzf.vim"
merged = 0

[[custom_plugins]]
# https://github.com/srstevenson/vim-picker
name = "srstevenson/vim-picker"
merged = 0

# ------------------------------------------------------------------------------
[[custom_plugins]]
# https://github.com/luochen1990/rainbow
name = "luochen1990/rainbow"
merged = 0

[[custom_plugins]]
# https://github.com/lilydjwg/colorizer
name = "lilydjwg/colorizer"
merged = 0

# [[custom_plugins]]
# # https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim
# name = "neoclide/coc.nvim"
# # :help dein-options
# build = "yarn install"
# # call coc#util#install()

[[custom_plugins]]
# https://github.com/mtth/scratch.vim
name = "mtth/scratch.vim"
merged = 0

[[custom_plugins]]
# https://github.com/tpope/vim-scriptease
name = "tpope/vim-scriptease"
merged = 0

# unimpaired
# https://spacevim.org/documentation/#unimpaired-bindings

[[custom_plugins]]
# https://github.com/justinmk/vim-dirvish
name = "justinmk/vim-dirvish"
merged = 0

# [[custom_plugins]]
# # https://github.com/tpope/vim-projectionist
# name = "tpope/vim-projectionist"
# merged = 0

[[custom_plugins]]
# https://github.com/GhostText/GhostText
# https://github.com/raghur/vim-ghost
name = "raghur/vim-ghost"

[[custom_plugins]]
# https://github.com/pelodelfuego/vim-swoop
name = "pelodelfuego/vim-swoop"

# ------------------------------------------------------------------------------
## utility ##

[[custom_plugins]]
# https://github.com/christianrondeau/vim-base64
name = "christianrondeau/vim-base64"

[[custom_plugins]]
# https://github.com/tyru/open-browser.vim
name = "tyru/open-browser.vim"

# ------------------------------------------------------------------------------
## tmux ##
# https://www.bugsnag.com/blog/tmux-and-vim, Tmux and Vim — even better together

[[custom_plugins]]
# https://github.com/christoomey/vim-tmux-navigator
name = "christoomey/vim-tmux-navigator"

[[custom_plugins]]
# https://github.com/benmills/vimux
name = "benmills/vimux"

[[custom_plugins]]
# http://kana.github.io/config/vim/arpeggio.html
name = "kana/vim-arpeggio"

[[custom_plugins]]
# https://github.com/edkolev/tmuxline.vim
name = "edkolev/tmuxline.vim"

# ------------------------------------------------------------------------------
## compatbility ##

# E117: Unknown function: yarp#py3, https://github.com/Shougo/deoplete.nvim/issues/727

[[custom_plugins]]
name = "roxma/nvim-yarp"

[[custom_plugins]]
name = "roxma/vim-hug-neovim-rpc"

# ------------------------------------------------------------------------------
## syntax ##

[[custom_plugins]]
# https://github.com/aklt/plantuml-syntax
name = "aklt/plantuml-syntax"
merged = 0

[[custom_plugins]]
# https://github.com/google/vim-jsonnet
name = "google/vim-jsonnet"
merged = 0

[[custom_plugins]]
# https://github.com/lepture/vim-jinja
name = "lepture/vim-jinja"
merged = 0

[[custom_plugins]]
# https://github.com/cespare/vim-toml
name = "cespare/vim-toml"
merged = 0

[[custom_plugins]]
# https://github.com/plasticboy/vim-markdown
name = "plasticboy/vim-markdown"
merged = 0

[[custom_plugins]]
# https://github.com/vim-jp/vim-java
name = "vim-jp/vim-java"
merged = 0

[[custom_plugins]]
# https://github.com/chr4/nginx.vim
name = "chr4/nginx.vim"
merged = 0

# ------------------------------------------------------------------------------
